name       : perl-getopt-long
version    : '2.54'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/J/JV/JV/Getopt-Long-2.54.tar.gz : 584ba3c99bb2d6b341375212f9b874613f706cfb01cee21b8a2676a98ab985fe
homepage   : https://metacpan.org/pod/Getopt::Long
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Getopt::Long - Extended processing of command line options
description: |
    The Getopt::Long module implements an extended getopt function called GetOptions(). It parses the command line from @ARGV, recognizing and removing specified options and their possible values.
rundeps    :
    - perl-pod-usage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
